### ISSUE TITLE
bug: takt fails to do the first check in from scratch.

### ISSUE THREAD

**Issue by emvalbuena** [mmngreco/takt#3]
takt fails to do the first check in from scratch.

From a clean installation and first use scenario, I did
```
takt check
```
which raised
```
FileNotFoundError: [Errno 2] No such file or directory: '/Users/username/.takt_file.csv'
```
To go around the issue, I created the file with `touch`
```
touch /Users/username/.takt_file.csv
```
and run `takt` again, getting the following issue
```
EmptyDataError: No columns to parse from file
```

**Comment by asdf8601** [comment]
use last commit from master and let me know if the problem persists ;-)
